=== Marco5de/PVS/SWC/file/WorldCupSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/WorldCupSchema" xmlns:tns="http://www.example.org/WorldCupSchema" elementFormDefault="qualified">

    <simpleType name="intPositive">
    	<restriction base="int">
    		<minInclusive value="0"></minInclusive>
    	</restriction>
    </simpleType>

    <complexType name="Team">
    	<sequence>
    		<element name="strName" type="string"></element>
    		<element name="points" type="tns:intPositive"></element>
    		<element name="gf" type="tns:intPositive"></element>
    		<element name="ga" type="tns:intPositive"></element>
    		<element name="played" type="tns:intPositive"></element>
    		<element name="won" type="tns:intPositive"></element>
    		<element name="lost" type="tns:intPositive"></element>
    		<element name="drawn" type="tns:intPositive"></element>
    	</sequence>
    </complexType>
    
    <complexType name="Game">
    	<sequence>
    		<element name="time" type="string"></element>
    		<element name="date" type="string"></element>
    		<element name="location" type="string"></element>
    		<element name="goalsH" type="tns:intPositive"></element>
    		<element name="goalsG" type="tns:intPositive"></element>
    		<element name="isPlayed" type="boolean"></element>
    		<element name="teamH" type="string"></element>
    		<element name="teamG" type="string"></element>
    	</sequence>
    	<attribute name="id" type="int"></attribute>
    </complexType>


    <complexType name="Group">
    	<sequence>
    	    <element name="groupName" type="string"></element>
    		<element name="teams" type="tns:Team" maxOccurs="4"
    			minOccurs="4">
    		</element>
    		<element name="games" type="tns:Game" minOccurs="6"
    			maxOccurs="6">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="Final">
    	<sequence>
    		<element name="roundOf16" type="tns:Game" maxOccurs="8"
    			minOccurs="8">
    		</element>
    		<element name="quarterFinals" type="tns:Game" minOccurs="4" maxOccurs="4"></element>
    		<element name="semiFinals" type="tns:Game" minOccurs="2"
    			maxOccurs="2">
    		</element>
    		<element name="thirdGame" type="tns:Game"></element>
    		<element name="finalGame" type="tns:Game"></element>
    	</sequence>
    </complexType>


    <complexType name="SoccerWC">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="groups" type="tns:Group" maxOccurs="8"
    			minOccurs="8">
    		</element>
    		<element name="finals" type="tns:Final" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="NewElement" type="string"></element>
    	</sequence>
    </complexType>

    <element name="worldCup" type="tns:SoccerWC"></element>


    <element name="team" type="tns:Team"></element>

    <element name="game" type="tns:Game"></element>

    <element name="group" type="tns:Group"></element>

    <element name="finals" type="tns:Final"></element>
</schema>

=== Marco5de/PVS/SWC/file/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:worldCup xmlns:tns="http://www.example.org/WorldCupSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/WorldCupSchema ../../../bin/swc/file/WorldCupSchema.xsd ">
  <tns:name>tns:name</tns:name>
  <tns:groups>
    <tns:groupName>tns:groupName</tns:groupName>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
  </tns:groups>
  <tns:groups>
    <tns:groupName>tns:groupName</tns:groupName>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
  </tns:groups>
  <tns:groups>
    <tns:groupName>tns:groupName</tns:groupName>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:teams>
      <tns:strName>tns:strName</tns:strName>
      <tns:points>0</tns:points>
      <tns:gf>0</tns:gf>
      <tns:ga>0</tns:ga>
      <tns:played>0</tns:played>
      <tns:won>0</tns:won>
      <tns:lost>0</tns:lost>
      <tns:drawn>0</tns:drawn>
    </tns:teams>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
    <tns:games>
      <tns:time>tns:time</tns:time>
      <tns:date>tns:date</tns:date>
      <tns:location>tns:location</tns:location>
      <tns:goalsH>0</tns:goalsH>
      <tns:goalsG>0</tns:goalsG>
      <tns:isPlayed>true</tns:isPlayed>
      <tns:teamH>tns:teamH</tns:teamH>
      <tns:teamG>tns:teamG</tns:teamG>
    </tns:games>
  </tns:groups>
  <tns:groups>
